        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 21 16:17:40 2019
        MODULE AB_BAN1__genmod
          INTERFACE 
            SUBROUTINE AB_BAN1(MODEL)
              INTEGER(KIND=4) :: MODEL
            END SUBROUTINE AB_BAN1
          END INTERFACE 
        END MODULE AB_BAN1__genmod
