        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 21 16:17:40 2019
        MODULE LEEPAR__genmod
          INTERFACE 
            SUBROUTINE LEEPAR(J,IREC1,IPAREQ,NGRUPA,ENASST,RKASST)
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: IREC1
              INTEGER(KIND=4) :: IPAREQ
              INTEGER(KIND=4) :: NGRUPA(150)
              REAL(KIND=8) :: ENASST
              REAL(KIND=8) :: RKASST
            END SUBROUTINE LEEPAR
          END INTERFACE 
        END MODULE LEEPAR__genmod
