        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 21 16:17:40 2019
        MODULE MAINSGFUNC__genmod
          INTERFACE 
            FUNCTION MAINSGFUNC(I1,IPAREQ) RESULT(MAINSGFUNC_0)
              INTEGER(KIND=4) :: I1
              INTEGER(KIND=4) :: IPAREQ
              INTEGER(KIND=4) :: MAINSGFUNC_0
            END FUNCTION MAINSGFUNC
          END INTERFACE 
        END MODULE MAINSGFUNC__genmod
