        !COMPILER-GENERATED INTERFACE MODULE: Mon Jul 23 15:27:21 2018
        MODULE LEERBASES__genmod
          INTERFACE 
            SUBROUTINE LEERBASES(NAME)
              CHARACTER(LEN=36) :: NAME
            END SUBROUTINE LEERBASES
          END INTERFACE 
        END MODULE LEERBASES__genmod
