        !COMPILER-GENERATED INTERFACE MODULE: Mon Jul 23 15:27:21 2018
        MODULE CR_PUNTF__genmod
          INTERFACE 
            SUBROUTINE CR_PUNTF(IGRUP,NPUNT,NGRUP,NPINT,NINTT)
              INTEGER(KIND=4), INTENT(IN) :: IGRUP
              INTEGER(KIND=4) :: NPUNT(150)
              INTEGER(KIND=4) :: NGRUP(150)
              INTEGER(KIND=4) :: NPINT(70)
              INTEGER(KIND=4) :: NINTT(70)
            END SUBROUTINE CR_PUNTF
          END INTERFACE 
        END MODULE CR_PUNTF__genmod
