//#region ram group category for for Liq./Liq.
export var grouposram_table1 =[
    ["None"],
    ["(CH3)","(CH2)","(CH)","(C)"],
    ["(CH2=CH)","(CH=CH)","(CH=C)","(CH2=C)"],
    ["(ACH)","(AC)"],
    ["(ACCH3)","(ACCH2)","(ACCH)"],
    ["(OH)"],
    ["(P1)"],
    ["(P2)"],
    ["(H2O)"],
    ["(ACOH)"],
    ["(CH3CO)","(CH2CO)"],
    ["(CHO)"],
    ["(FURF)"],
    ["(COOH)","(HCOOH)"],
    ["(CH3COO)","(CH2COO)"],
    ["(CH3O)","(CH2O)","(CH-O)","(FCH2O)"],
    ["(CH2CL)","(CHCL)","(CCL)"],
    ["(CH2CL2)","(CHCL2)","(CCL2)"],
    ["(CHCL3)","(CCL3)"],
    ["(CCL4)"],
    ["(ACCL)"],
    ["(CH3CN)","(CH2CN)"],
    ["(ACNH2)"],
    ["(CH3NO2)","(CH2NO2)","(CHNO2)"],
    ["(ACNO2)"],
    ["(CH2OH)2"],
    ["(DEOH)"],
    ["(C5H5N)","(C5H4N)","(C5H3N)"],
    ["(TCLE)"],
    ["(MFA)"],
    ["(DMFA)"],
    ["(TMS)"],
    ["(ME2SO)"]
];
//#endregion

//#region ram group category for for Vap./Liq.
export var grouposram_table2 =[
    ["None"],
    ["(CH3)","(CH2)","(CH)","(C)"],
    ["(CH2=CH)","(CH=CH)","(CH2=C)","(CH=C)","(C=C)"],
    ["(ACH)","(AC)"],
    ["(ACCH3)","(ACCH2)","(ACCH)"],
    ["(OH)"],
    ["(CH3OH)"],
    ["(H2O)"],
    ["(ACOH)"],
    ["(CH3CO)","(CH2CO)"],
    ["(CHO)"],
    ["(CH3COO)","(CH2COO)"],
    ["(HCOO)"],
    ["(CH3O)","(CH2O)","(CH-O)","(FCH2O)"],
    ["(CH3NH2)","(CH2NH2)","(CHNH2)"],
    ["(CH3NH)","(CH2NH)","(CHNH)"],
    ["(CH3N)","(CH2N)"],
    ["(ACNH2)"],
    ["(C5H5N)","(C5H4N)","(C5H3N)"],
    ["(CH3CN)","(CH2CN)"],
    ["(COOH)","(HCOOH)"],
    ["(CH2CL)","(CHCL)","(CCL)"],
    ["(CH2CL2)","(CHCL2)","(CCL2)"],
    ["(CHCL3)","(CCL3)"],
    ["(CCL4)"],
    ["(ACCL)"],
    ["(CH3NO2)","(CH2NO2)","(CHNO2)"],
    ["(ACNO2)"],
    ["(CS2)"],
    ["(CH3SH)","(CH2SH)"],
    ["(FURF)"],
    ["(CH2OH)2"],
    ["(I)"],
    ["(BR)"],
    ["(CH=-C)","(C=-C)"],
    ["(ME2SO)"],
    ["(ACRY)"],
    ["CL-C=C)"],
    ["(ACF)"],
    ["(DMFA)","(DMF-2)"],
    ["(CF3)","(CF2)","(CF)"],
    ["(COO)"],
    ["(SIH3)","(SIH2)","(SIH)","(SI)"],
    ["(SIH2O)","(SIHO)","(SIO)"]
];

//#endregion

//#region ram group category for for Inf.Dil
export var grouposram_table3 =[
    ["None"],
    ["(CH3)","(CH2)","(CH)","(C)"],
    ["(CH2=CH)","(CH=CH)","(CH2=C)","(CH=C)","(C=C)"],
    ["(ACH)","(AC)"],
    ["(ACCH3)","(ACCH2)","(ACCH)"],
    ["(OH)"],
    ["(CH3OH)"],
    ["(H2O)"],
    ["(ACOH)"],
    ["(CH3CO)","(CH2CO)"],
    ["(CHO)"],
    ["(CH3COO)","(CH2COO)"],
    ["(HCOO)"],
    ["(CH3O)","(CH2O)","(CH-O)","(FCH2O)"],
    ["(CH3NH2)","(CH2NH2)","(CHNH2)"],
    ["(CH3N)","(CH2N)"],
    ["(ACNH2)"],
    ["(C5H5N)","(C5H4N)","(C5H3N)","(C5H2N)"],
    ["(CH3CN)","(CH2CN)"],
    ["(CH2CL)","(CHCL)","(CCL)"],
    ["(CH2CL2)","(CHCL2)","(CCL2)"],
    ["(CHCL3)","(CCL3)"],
    ["(CCL4)"],
    ["(ACCL)"],
    ["(CH3NO2)","(CH2NO2)","(CHNO2)","(CNO2)"],
    ["(ACNO2)"],
    ["(FURF)"],
    ["(CH2OH)2"],
    ["(I)"],
    ["(BR)"],
    ["(ME2SO)"],
    ["CL-(C=C)"],
    ["(DMFA)"],
    ["(NMP)"],
    ["(SULFOL)"],
    ["(ACCOO)"],
    ["(CH3S)","(CH2S)"],
    ["(DMA)"],
    ["(DEOH)"],
    ["(NFM)"],
    ["(TEG)"]
];

//#endregion


//#region intrcn table for Liq./Liq.
export var intrcn_table1 = [
    [0,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32],
    [1],
    [2],
    [3],
    [4],
    [5],
    [6],
    [7],
    [8],
    [9],
    [10],
    [11],
    [12],
    [13],
    [14],
    [15],
    [16],
    [17],
    [18],
    [19],
    [20],
    [21],
    [22],
    [23],
    [24],
    [25],
    [26],
    [27],
    [28],
    [29],
    [30],
    [31],
    [32],
];

//#endregion
//#region intrcn table for Vap./Liq.
export var intrcn_table2 = [];

//#endregion

//#region intrcn table for Inf.Dil.
export var intrcn_table3 = [];

//#endregion